### ISSUE TITLE
Change the value of AuthnCacheContext?

### ISSUE THREAD

**Issue by ghost** [ManageIQ/container-httpd#40]
Thanks for providing the container! I have a question about one httpd config:`AuthnCacheContext`.
It seems the [official document](https://httpd.apache.org/docs/current/mod/mod_authn_socache.html#authncachecontext) recommends to change the default `directory`, which is conservative and not optimal. **A better policy is to name the `AuthnCacheContext` for the password provider: for example a htpasswd file or database table.**

Maybe it's better to set that to specify a context string for use in the cache keyin the comfig file? Thanks.

**Comment by mfeifer** [comment]
cc @carbonin

**Comment by carbonin** [comment]
It doesn't look like we're using this value at all.

Looks like another case of a bot just spamming a bunch of httpd related repos:
![image](https://user-images.githubusercontent.com/12697904/68888744-8236d680-06e9-11ea-9c31-ce5baafb2c96.png)
