### ISSUE TITLE
Update ruby version in image

### ISSUE THREAD

**Issue by simaishi** [ManageIQ/container-httpd#41]
The image is currently using ruby 2.3 which is EOL. We should update to 2.5.5 or later (2.5.5 is what container-ruby is currently at).

Maybe we should also change to run ruby-install with --system (just like https://github.com/ManageIQ/manageiq-appliance-build/pull/234)?

**Comment by carbonin** [comment]
Even bigger issue, https://copr.fedorainfracloud.org/coprs/postmodern/ruby-install/repo/fedora-25/postmodern-ruby-install-fedora-25.repo doesn't exist anymore so this image will not build.

**Comment by simaishi** [comment]
> Even bigger issue, https://copr.fedorainfracloud.org/coprs/postmodern/ruby-install/repo/fedora-25/postmodern-ruby-install-fedora-25.repo doesn't exist anymore so this image will not build.

It's in our copr repo now, so we need to take this change too... https://github.com/ManageIQ/container-ruby/pull/12
