### ISSUE TITLE
How to use with manageiq-pods Ivanchuk release?

### ISSUE THREAD

**Issue by carsten-a1** [ManageIQ/container-httpd#50]
Rework done to run as unprivileged user is much appreciated.

Sample templates for manageiq-pods in Ivanchuk release refer to docker.io/manageiq/httpd:latest and httpd pod fails to start (in openshift).

Is it possible to provide compatibility with Ivanchuk release or get guidance on how to make it work?

Many thanks in advance for your help!

**Comment by carbonin** [comment]
@miq-bot move_issue manageiq/manageiq-pods

**Comment by carbonin** [comment]
Guess @miq-bot isn't listening in this repo. :worried:
